# Generated by Django 4.0 on 2021-12-29 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='حقوق ماه')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pure_income', models.PositiveIntegerField(verbose_name='درآمد مربوط به سفر')),
                ('date', models.DateField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_calculator.courier')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_raise', models.PositiveIntegerField(verbose_name='افزایش درآمد')),
                ('income_reduce', models.PositiveIntegerField(verbose_name='کسر از درآمد')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_calculator.trip')),
            ],
        ),
        migrations.CreateModel(
            name='DailySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='حقوق روز')),
                ('date', models.DateField()),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='income_calculator.courier')),
            ],
        ),
    ]
