# Generated by Django 4.0 on 2021-12-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0002_remove_salarychange_trip_delete_weeklysalary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysalary',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='courier',
        ),
    ]
