# Generated by Django 4.0 on 2021-12-29 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0006_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='حقوق روز')),
                ('date', models.DateField()),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='income_calculator.courier')),
            ],
        ),
    ]
