# Generated by Django 4.0 on 2021-12-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0008_remove_dailysalary_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalary',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='حقوق روز'),
        ),
    ]
