# Generated by Django 4.0 on 2021-12-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0009_dailysalary_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
