# Generated by Django 4.0 on 2021-12-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0011_alter_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
