# Generated by Django 4.0 on 2021-12-29 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0014_alter_dailysalary_date_alter_trip_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysalary',
            name='salary',
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 12, 43, 32, 248635)),
        ),
    ]
