# Generated by Django 4.0 on 2021-12-29 12:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0018_dailysalary_salary_alter_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='date',
            field=models.DateField(db_index=True, default=None),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 12, 29, 12, 52, 53, 667095)),
        ),
        migrations.CreateModel(
            name='SalaryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_raise', models.PositiveIntegerField(verbose_name='افزایش درآمد')),
                ('income_reduce', models.PositiveIntegerField(verbose_name='کسر از درآمد')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_calculator.trip')),
            ],
        ),
    ]
