# Generated by Django 4.0 on 2021-12-29 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0021_alter_trip_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysalary',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_calculator.courier'),
        ),
    ]
