# Generated by Django 4.0 on 2021-12-29 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0022_alter_dailysalary_courier'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturday_date', models.DateField(db_index=True, default=None)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_calculator.courier')),
            ],
        ),
    ]
