# Generated by Django 4.0 on 2021-12-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_calculator', '0024_weeklysalary_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklysalary',
            old_name='saturday_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='weeklysalary',
            name='salary',
            field=models.IntegerField(default=0, verbose_name='حقوق هفته'),
        ),
    ]
